"""empty message

Revision ID: 666683b95a8e
Revises: 5f9bea3c6bd2
Create Date: 2021-10-21 18:44:16.880212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666683b95a8e'
down_revision = '5f9bea3c6bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('listing_id', sa.Integer(), nullable=False))
    op.add_column('images', sa.Column('image_url', sa.Text(), nullable=False))
    op.add_column('images', sa.Column('created_at', sa.Date(), nullable=False))
    op.add_column('images', sa.Column('updated_at', sa.Date(), nullable=False))
    op.drop_constraint('images_listingId_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'listings', ['listing_id'], ['id'])
    op.drop_column('images', 'listingId')
    op.drop_column('images', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('listingId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_listingId_fkey', 'images', 'listings', ['listingId'], ['id'])
    op.drop_column('images', 'updated_at')
    op.drop_column('images', 'created_at')
    op.drop_column('images', 'image_url')
    op.drop_column('images', 'listing_id')
    # ### end Alembic commands ###
