"""empty message

Revision ID: 5f9bea3c6bd2
Revises: 2ddb2fd348d2
Create Date: 2021-10-20 00:11:39.638788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9bea3c6bd2'
down_revision = '2ddb2fd348d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('listings_userId_fkey', 'listings', type_='foreignkey')
    op.create_foreign_key(None, 'listings', 'users', ['user_id'], ['id'])
    op.drop_column('listings', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.create_foreign_key('listings_userId_fkey', 'listings', 'users', ['userId'], ['id'])
    op.drop_column('listings', 'user_id')
    # ### end Alembic commands ###
