"""empty message

Revision ID: 01ab6fe1838f
Revises: e5c51b16b7b4
Create Date: 2021-10-19 23:15:49.847702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ab6fe1838f'
down_revision = 'e5c51b16b7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'title')
    # ### end Alembic commands ###
