"""empty message

Revision ID: e5c51b16b7b4
Revises: 29876990d6da
Create Date: 2021-10-19 23:10:28.863542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c51b16b7b4'
down_revision = '29876990d6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'image')
    # ### end Alembic commands ###
